### ISSUE TITLE
Deprecated Blaze calls in Chrome.

### ISSUE THREAD

**Issue by ForwardLabs** [projik/meteor-camera#1]
When using this package with projik/camera-ui, there are deprecated Blaze.render and Blaze.insert calls. These appear to have been resolved with the following:

To fix the deprecated warnings the last 2 lines in photo-browser.js:

`- 209. view = UI.renderWithData(Template.camera);`
`- 210. UI.insert(view, document.body);`

should be changed to single line:

`- 209. view = Blaze.render(Template.camera, document.body);`

via [https://github.com/meteor/mobile-packages/issues/91](url)

PS - Thanks for updating projik/camera-ui to work with Meteor 1.4!

**Comment by projik** [comment]
Thanks Rob. I've pushed that change, available in version 1.4.3.
