### ISSUE TITLE
Customize UI with "camera-ui" package

### ISSUE THREAD

**Issue by ForwardLabs** [projik/meteor-camera#2]
I might be missing something here, so please excuse if this is an obvious answer.

Q1) I'm using the your "camera-ui" package as well and wondering if there's a way to pass in a new UI template (photo.html) via the browser options? If not, is there a way to customize the UI without editing the package source?

Q2) Are there additional browser options other than height + width?

Q3) Is there a way to customize the size of the viewfinder without editing the package source? Currently it looks to be hard-coded to 320x240.

Thanks in advance!

**Comment by projik** [comment]
Hi Rob,

1) You can use the aldeed:template-extension package (
https://atmospherejs.com/aldeed/template-extension) to override templates
in plugins without having to change the source code. For example if you
wanted to replace the 'camera' template in supaseca-camera, you would
create your own template (for example 'override-camera') and then use the
template-extension plugin to override the original template. E.g:

Template.override-camera.replaces('camera');

2) The available options are height, width and quality (of picture, 1 - 100)

3) You can customise the size of the viewfinder by using css, which will
override the element attributes. You need to keep in mind the the
viewfinder will only display in a 4:3 / width:height ratio so you need to
make sure the the width and height you set by css use that ratio. E.g.:

#video {
    width: 480px;
    height: 360px;
}

**Comment by ForwardLabs** [comment]
Awesome. Thank you for the detailed reply!
